CREATE SCHEMA CONFORM;

-- Table for cleaned OpenPlanet data
CREATE TABLE CONFORM.TMIO (
    TOTD_YEAR INTEGER,
    TOTD_MONTH INTEGER,
    TOTD_DAY INTEGER,
    MAP_UID VARCHAR(50) PRIMARY KEY,
    EXCHANGE_ID INTEGER,
    AUTHOR_NAME VARCHAR(50),
    AUTHOR_ID VARCHAR(50),
    AUTHOR_TIME FLOAT,
    GOLD_TIME FLOAT,
    SILVER_TIME FLOAT,
    BRONZE_TIME FLOAT,
    SUBMITTER_NAME VARCHAR(50),
    SUBMITTER_ID VARCHAR(50),
    UPLOADED_YEAR INTEGER,
    UPLOADED_MONTH INTEGER,
    UPLOADED_DAY INTEGER,
    LEADERBOARD_UID VARCHAR(50)
);

-- Table for cleaned OpenPlanet leaderboard data
CREATE TABLE CONFORM.TMIO_LEADERBOARDS (
    EXCHANGE_ID INTEGER NOT NULL,
    PLAYER_NAME VARCHAR(50),
    PLAYER_ID VARCHAR(50),
    REPLAY_TIME FLOAT,
    UPLOADED_YEAR INTEGER,
    UPLOADED_MONTH INTEGER,
    UPLOADED_DAY INTEGER,
    UNIQUE(EXCHANGE_ID, PLAYER_ID)
);

-- Table for cleaned TMX data
CREATE TABLE CONFORM.TMX (
    MAP_UID VARCHAR(50) PRIMARY KEY,
    TRACK_ID INTEGER,
    MAP_NAME VARCHAR(200),
    STYLE_NAME VARCHAR(50),
    DIFFICULTY_NAME VARCHAR(50),
    MAP_TAGS INTEGER ARRAY,
    LAPS INTEGER,
    UPLOADED_YEAR INTEGER,
    UPLOADED_MONTH INTEGER,
    UPLOADED_DAY INTEGER,
    UPDATED_YEAR INTEGER,
    UPDATED_MONTH INTEGER,
    UPDATED_DAY INTEGER
);

-- Table for cleaned TMX authors data
CREATE TABLE CONFORM.TMX_AUTHORS (
    TRACK_ID INTEGER NOT NULL,
    USERNAME VARCHAR(50),
    AUTHOR_ROLE VARCHAR(50),
    UNIQUE(TRACK_ID, USERNAME)
);
