CREATE SCHEMA CONSUME;

-- Base table for TOTD data. Some joins required to find tags, full authors list, leaderboards, etc.
CREATE TABLE CONSUME.TOTD (
    TOTD_DATE DATE,
    TOTD_DAY_OF_WEEK VARCHAR(10),
    EXCHANGE_ID INTEGER,
    MAP_NAME VARCHAR(200),
    IS_MULTILAP_FLAG BOOLEAN,
    AUTHOR_TIME FLOAT,
    GOLD_TIME FLOAT,
    SILVER_TIME FLOAT,
    BRONZE_TIME FLOAT,
    UPLOADED_DATE DATE,
    DAYS_BEFORE_TOTD INTEGER,
    UNIQUE(TOTD_DATE, EXCHANGE_ID)
);

-- Table for all tags associated with a TOTD map
CREATE TABLE CONSUME.TOTD_TAGS (
    EXCHANGE_ID INTEGER,
    TAG_NAME VARCHAR(50),
    UNIQUE(EXCHANGE_ID, TAG_NAME)
);

-- Table for all authors on all TOTD maps
CREATE TABLE CONSUME.TOTD_AUTHORS (
    EXCHANGE_ID INTEGER,
    USERNAME VARCHAR(50),
    USER_ID VARCHAR(50),
    AUTHOR_ROLE VARCHAR(200),
    UNIQUE(EXCHANGE_ID, USERNAME)
);

-- Table for all TOTD world records. Saves a lot of painful aggregate queries
CREATE TABLE CONSUME.TOTD_WORLDRECORDS (
    EXCHANGE_ID INTEGER,
    USERNAME VARCHAR(50),
    USER_ID VARCHAR(50),
    REPLAY_TIME FLOAT,
    DRIVEN_DATE DATE,
    UNIQUE(EXCHANGE_ID, USER_ID)
);

