CREATE SCHEMA COLLECT;
CREATE SCHEMA CONFORM;
CREATE SCHEMA CONSUME;
CREATE SCHEMA APP;

-- Table for raw data from OpenPlanet API call
CREATE TABLE COLLECT.TMIO_RAW (
    DATA_YEAR INTEGER,
    DATA_MONTH INTEGER,
    DATA_DAY INTEGER,
    JSON_DATA TEXT,
    UNIQUE(DATA_YEAR, DATA_MONTH, DATA_DAY)
);

-- Table for cleaned OpenPlanet data
CREATE TABLE CONFORM.TMIO_CLEANED (
    TOTD_YEAR INTEGER,
    TOTD_MONTH INTEGER,
    TOTD_DAY INTEGER,
    TOTD_DAY_OF_WEEK VARCHAR(10),
    MAP_ID VARCHAR(50) PRIMARY KEY,
    EXCHANGE_ID INTEGER,
    AUTHOR_NAME VARCHAR(50),
    AUTHOR_ID VARCHAR(50),
    AUTHOR_TIME FLOAT,
    GOLD_TIME FLOAT,
    SILVER_TIME FLOAT,
    BRONZE_TIME FLOAT,
    SUBMITTER_NAME VARCHAR(50),
    SUBMITTER_ID VARCHAR(50),
    UPLOADED_YEAR INTEGER,
    UPLOADED_MONTH INTEGER,
    UPLOADED_DAY INTEGER,
    UPLOADED_DAY_OF_WEEK VARCHAR(10)
)