CREATE SCHEMA COLLECT;
CREATE SCHEMA CONFORM;
CREATE SCHEMA CONSUME;
CREATE SCHEMA APP;

-- Table for raw data from OpenPlanet API call
CREATE TABLE COLLECT.TMIO_RAW (
    DATA_YEAR INTEGER,
    DATA_MONTH INTEGER,
    DATA_DAY INTEGER,
    JSON_DATA TEXT,
    UNIQUE(DATA_YEAR, DATA_MONTH, DATA_DAY)
);

-- Table for raw data from TMX API call
CREATE TABLE COLLECT.TMX_RAW (
    MAP_UID VARCHAR(50) PRIMARY KEY,
    JSON_DATA TEXT
);

-- Table for cleaned OpenPlanet data
CREATE TABLE CONFORM.TMIO_CLEANED (
    TOTD_YEAR INTEGER,
    TOTD_MONTH INTEGER,
    TOTD_DAY INTEGER,
    TOTD_DAY_OF_WEEK VARCHAR(10),
    MAP_UID VARCHAR(50) PRIMARY KEY,
    EXCHANGE_ID INTEGER,
    AUTHOR_NAME VARCHAR(50),
    AUTHOR_ID VARCHAR(50),
    AUTHOR_TIME FLOAT,
    GOLD_TIME FLOAT,
    SILVER_TIME FLOAT,
    BRONZE_TIME FLOAT,
    SUBMITTER_NAME VARCHAR(50),
    SUBMITTER_ID VARCHAR(50),
    UPLOADED_YEAR INTEGER,
    UPLOADED_MONTH INTEGER,
    UPLOADED_DAY INTEGER,
    UPLOADED_DAY_OF_WEEK VARCHAR(10)
);

-- Table for cleaned TMX data
CREATE TABLE CONFORM.TMX_CLEANED (
    MAP_UID VARCHAR(50) PRIMARY KEY,
    TRACK_ID INTEGER,
    MAP_NAME VARCHAR(200),
    STYLE_NAME VARCHAR(50),
    DIFFICULTY_NAME VARCHAR(50),
    LAPS INTEGER,
    USER_ID INTEGER,
    USERNAME VARCHAR(50),
    UPLOADED_YEAR INTEGER,
    UPLOADED_MONTH INTEGER,
    UPLOADED_DAY INTEGER,
    UPLOADED_DAY_OF_WEEK VARCHAR(10),
    UPDATED_YEAR INTEGER,
    UPDATED_MONTH INTEGER,
    UPDATED_DAY INTEGER,
    UPDATED_DAY_OF_WEEK VARCHAR(10),
    AUTHOR_TIME FLOAT,
    WR_TIME FLOAT,
    WR_USER_ID INTEGER,
    WR_USERNAME VARCHAR(50)
);