CREATE SCHEMA COLLECT;
CREATE SCHEMA CONFORM;
CREATE SCHEMA CONSUME;
CREATE SCHEMA APP;

-- Table for raw data from OpenPlanet API call
CREATE TABLE COLLECT.TMIO_RAW (
    DATA_YEAR INTEGER,
    DATA_MONTH INTEGER,
    DATA_DAY INTEGER,
    JSON_DATA TEXT,
    UNIQUE(DATA_YEAR, DATA_MONTH, DATA_DAY)
);

-- Table for raw data from TMX API call
CREATE TABLE COLLECT.TMX_RAW (
    MAP_UID VARCHAR(50) PRIMARY KEY,
    JSON_DATA TEXT
);

-- Table for raw data from TMX authors API call
CREATE TABLE COLLECT.TMX_AUTHORS_RAW (
    TRACK_ID INTEGER PRIMARY KEY,
    JSON_DATA TEXT
);

-- Table for raw data from TMX leaderboards API call
CREATE TABLE COLLECT.TMX_REPLAYS_RAW (
    TRACK_ID INTEGER PRIMARY KEY,
    JSON_DATA TEXT
);


-- Table for cleaned OpenPlanet data
CREATE TABLE CONFORM.TMIO_CLEANED (
    TOTD_YEAR INTEGER,
    TOTD_MONTH INTEGER,
    TOTD_DAY INTEGER,
    MAP_UID VARCHAR(50) PRIMARY KEY,
    EXCHANGE_ID INTEGER,
    AUTHOR_NAME VARCHAR(50),
    AUTHOR_ID VARCHAR(50),
    AUTHOR_TIME FLOAT,
    GOLD_TIME FLOAT,
    SILVER_TIME FLOAT,
    BRONZE_TIME FLOAT,
    SUBMITTER_NAME VARCHAR(50),
    SUBMITTER_ID VARCHAR(50),
    UPLOADED_YEAR INTEGER,
    UPLOADED_MONTH INTEGER,
    UPLOADED_DAY INTEGER
);

-- Table for cleaned TMX data
CREATE TABLE CONFORM.TMX_CLEANED (
    MAP_UID VARCHAR(50) PRIMARY KEY,
    TRACK_ID INTEGER,
    MAP_NAME VARCHAR(200),
    STYLE_NAME VARCHAR(50),
    DIFFICULTY_NAME VARCHAR(50),
    MAP_TAGS INTEGER ARRAY,
    LAPS INTEGER,
    UPLOADED_YEAR INTEGER,
    UPLOADED_MONTH INTEGER,
    UPLOADED_DAY INTEGER,
    UPDATED_YEAR INTEGER,
    UPDATED_MONTH INTEGER,
    UPDATED_DAY INTEGER,
    WR_TIME FLOAT,
    WR_USER_ID INTEGER,
    WR_USERNAME VARCHAR(50)
);

-- Table for cleaned TMX authors data
CREATE TABLE CONFORM.TMX_AUTHORS_CLEANED (
    TRACK_ID INTEGER,
    USER_ID INTEGER,
    USERNAME VARCHAR(50),
    AUTHOR_ROLE VARCHAR(50),
    UNIQUE(TRACK_ID, USER_ID)
);

-- Table for cleaned TMX replay data
CREATE TABLE CONFORM.TMX_REPLAYS_CLEANED (
    REPLAY_ID INTEGER PRIMARY KEY,
    TRACK_ID INTEGER,
    USER_ID INTEGER,
    USERNAME VARCHAR(50),
    UPLOADED_YEAR INTEGER,
    UPLOADED_MONTH INTEGER,
    UPLOADED_DAY INTEGER,
    REPLAY_TIME FLOAT,
    RESPAWNS INTEGER
);
